apiVersion: apps/v1
kind: Deployment
metadata:
  name: yurii-site-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yurii-site
  template:
    metadata:
      labels:
        app: yurii-site
    spec:
      containers:
      - name: yurii-site
        image: YuriiStaroselets/yurii-site-hub:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: yurii-site-service
spec:
  selector:
    app: yurii-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

