# Generated by Django 4.0.5 on 2023-07-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
